name: Deploy Ionic App

on:
  pull_request:
    types: [opened,closed]
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19'

    - name: Install dependencies
      run: |
        cd App_Movil_Paraleos_Futbol/AppParalelos
        npm install

    - name: Build Ionic app
      run: |
        cd App_Movil_Paraleos_Futbol/AppParalelos
        npm run build

    - name: Deploy to server
      env:
        HOST: "146.190.219.72"
        USERNAME: root
        KEY: ${{ secrets.SSH_KEY }} #calve ssh2
      run: |
        echo "$KEY" > my_ssh_key
        chmod 600 my_ssh_key
        scp -i my_ssh_key -r App_Movil_Paraleos_Futbol/AppParalelos/www/* $USERNAME@$HOST:/App_Movil_Paraleos_Futbol/AppParalelos/
        ssh -i my_ssh_key $USERNAME@$HOST "echo 'SSH connection successful'"
