name: Deploy Ionic App

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19'

    - name: Install dependencies
      run: |
        cd App_Movil_Paraleos_Futbol/AppParalelos
        npm install

    - name: Build Ionic app
      run: |
        cd App_Movil_Paraleos_Futbol/AppParalelos
        npm run build
    - name: Create SSH key
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          sudo chmod 600 ~/.ssh/known_hosts
      shell: bash
      env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
    - name: Deploy to server
      env:
        HOST: "146.190.219.72"
        USERNAME: root
      run: |
        scp -i "$SSH_PRIVATE_KEY" -r App_Movil_Paraleos_Futbol/AppParalelos/www/* $USERNAME@$HOST:/path/to/deployment/App_Movil_Paraleos_Futbol/AppParalelos/
        ssh -i "$SSH_PRIVATE_KEY" $USERNAME@$HOST "cd /path/to/deployment/App_Movil_Paraleos_Futbol/AppParalelos && npm install"
